apiVersion: v1
kind: Service
metadata:
  name: pet-mysql
spec:
  selector:
    component: pet-mysql
  ports:
    - port: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pet-mysql-pv-volume
  labels:
    app: petclinic
spec:
  storageClassName: mysql
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pet-mysql-pvc
  labels:
    app: petclinic
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-mysql-deployment
spec:
  selector:
    matchLabels:
      component: pet-mysql
  template:
    metadata:
      labels:
        component: pet-mysql
    spec:
      nodeSelector:
        group: db
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: pet-mysql-pvc
      containers:
        - name: client
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: petclinic
            - name: MYSQL_USER
              value: petclinic
            - name: MYSQL_PASSWORD
              value: petclinic
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: '1'
